# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'research.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 725)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.simulation_setup = QtWidgets.QVBoxLayout()
        self.simulation_setup.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.simulation_setup.setObjectName("simulation_setup")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(265, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(275, 16777215))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 265, 493))
        self.page.setObjectName("page")
        self.formLayout_2 = QtWidgets.QFormLayout(self.page)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.path = QtWidgets.QPushButton(self.page)
        self.path.setObjectName("path")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.path)
        self.name = QtWidgets.QPlainTextEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name.sizePolicy().hasHeightForWidth())
        self.name.setSizePolicy(sizePolicy)
        self.name.setMinimumSize(QtCore.QSize(0, 20))
        self.name.setMaximumSize(QtCore.QSize(16777215, 25))
        self.name.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.name.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.name.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.name.setTabChangesFocus(False)
        self.name.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.name.setObjectName("name")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 252, 653))
        self.page_2.setObjectName("page_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(-1, 6, -1, -1)
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setVerticalSpacing(3)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.struct_name_norm = QtWidgets.QPlainTextEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.struct_name_norm.sizePolicy().hasHeightForWidth())
        self.struct_name_norm.setSizePolicy(sizePolicy)
        self.struct_name_norm.setMinimumSize(QtCore.QSize(135, 25))
        self.struct_name_norm.setMaximumSize(QtCore.QSize(135, 20))
        self.struct_name_norm.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.struct_name_norm.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.struct_name_norm.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.struct_name_norm.setObjectName("struct_name_norm")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.struct_name_norm)
        self.label_7 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.bravais_lattice = QtWidgets.QComboBox(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bravais_lattice.sizePolicy().hasHeightForWidth())
        self.bravais_lattice.setSizePolicy(sizePolicy)
        self.bravais_lattice.setMinimumSize(QtCore.QSize(135, 0))
        self.bravais_lattice.setObjectName("bravais_lattice")
        self.bravais_lattice.addItem("")
        self.bravais_lattice.setItemText(0, "")
        self.bravais_lattice.addItem("")
        self.bravais_lattice.addItem("")
        self.bravais_lattice.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bravais_lattice)
        self.label_8 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lattice_constant_norm = QtWidgets.QPlainTextEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lattice_constant_norm.sizePolicy().hasHeightForWidth())
        self.lattice_constant_norm.setSizePolicy(sizePolicy)
        self.lattice_constant_norm.setMaximumSize(QtCore.QSize(135, 25))
        self.lattice_constant_norm.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lattice_constant_norm.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lattice_constant_norm.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.lattice_constant_norm.setObjectName("lattice_constant_norm")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lattice_constant_norm)
        self.show_structure_norm = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_structure_norm.sizePolicy().hasHeightForWidth())
        self.show_structure_norm.setSizePolicy(sizePolicy)
        self.show_structure_norm.setObjectName("show_structure_norm")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.show_structure_norm)
        self.save_structure_norm = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_structure_norm.sizePolicy().hasHeightForWidth())
        self.save_structure_norm.setSizePolicy(sizePolicy)
        self.save_structure_norm.setMaximumSize(QtCore.QSize(135, 16777215))
        self.save_structure_norm.setObjectName("save_structure_norm")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.save_structure_norm)
        self.verticalLayout.addLayout(self.formLayout)
        self.label_4 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(-1, 6, -1, -1)
        self.formLayout_3.setHorizontalSpacing(0)
        self.formLayout_3.setVerticalSpacing(3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.struct_name_bulk = QtWidgets.QPlainTextEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.struct_name_bulk.sizePolicy().hasHeightForWidth())
        self.struct_name_bulk.setSizePolicy(sizePolicy)
        self.struct_name_bulk.setMinimumSize(QtCore.QSize(0, 25))
        self.struct_name_bulk.setMaximumSize(QtCore.QSize(132, 20))
        self.struct_name_bulk.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.struct_name_bulk.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.struct_name_bulk.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.struct_name_bulk.setObjectName("struct_name_bulk")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.struct_name_bulk)
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.page_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lattice_constant_bulk = QtWidgets.QPlainTextEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lattice_constant_bulk.sizePolicy().hasHeightForWidth())
        self.lattice_constant_bulk.setSizePolicy(sizePolicy)
        self.lattice_constant_bulk.setMinimumSize(QtCore.QSize(0, 25))
        self.lattice_constant_bulk.setMaximumSize(QtCore.QSize(132, 20))
        self.lattice_constant_bulk.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lattice_constant_bulk.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lattice_constant_bulk.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.lattice_constant_bulk.setObjectName("lattice_constant_bulk")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lattice_constant_bulk)
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.show_structure_bulk = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_structure_bulk.sizePolicy().hasHeightForWidth())
        self.show_structure_bulk.setSizePolicy(sizePolicy)
        self.show_structure_bulk.setMinimumSize(QtCore.QSize(116, 0))
        self.show_structure_bulk.setMaximumSize(QtCore.QSize(132, 16777215))
        self.show_structure_bulk.setObjectName("show_structure_bulk")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.show_structure_bulk)
        self.save_structure_bulk = QtWidgets.QPushButton(self.page_2)
        self.save_structure_bulk.setMaximumSize(QtCore.QSize(132, 16777215))
        self.save_structure_bulk.setObjectName("save_structure_bulk")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.save_structure_bulk)
        self.crystal_structure = QtWidgets.QComboBox(self.page_2)
        self.crystal_structure.setMaximumSize(QtCore.QSize(132, 16777215))
        self.crystal_structure.setObjectName("crystal_structure")
        self.crystal_structure.addItem("")
        self.crystal_structure.setItemText(0, "")
        self.crystal_structure.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.crystal_structure)
        self.crystal_system = QtWidgets.QComboBox(self.page_2)
        self.crystal_system.setMaximumSize(QtCore.QSize(132, 16777215))
        self.crystal_system.setObjectName("crystal_system")
        self.crystal_system.addItem("")
        self.crystal_system.setItemText(0, "")
        self.crystal_system.addItem("")
        self.crystal_system.addItem("")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.crystal_system)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.label_5 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setContentsMargins(-1, 6, 0, -1)
        self.formLayout_4.setHorizontalSpacing(0)
        self.formLayout_4.setVerticalSpacing(3)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.struct_name_spacegroup = QtWidgets.QPlainTextEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.struct_name_spacegroup.sizePolicy().hasHeightForWidth())
        self.struct_name_spacegroup.setSizePolicy(sizePolicy)
        self.struct_name_spacegroup.setMinimumSize(QtCore.QSize(0, 25))
        self.struct_name_spacegroup.setMaximumSize(QtCore.QSize(133, 25))
        self.struct_name_spacegroup.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.struct_name_spacegroup.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.struct_name_spacegroup.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.struct_name_spacegroup.setObjectName("struct_name_spacegroup")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.struct_name_spacegroup)
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.element_1 = QtWidgets.QPlainTextEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element_1.sizePolicy().hasHeightForWidth())
        self.element_1.setSizePolicy(sizePolicy)
        self.element_1.setMinimumSize(QtCore.QSize(0, 25))
        self.element_1.setMaximumSize(QtCore.QSize(133, 25))
        self.element_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.element_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.element_1.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.element_1.setObjectName("element_1")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.element_1)
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.basis_1_1 = QtWidgets.QPlainTextEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basis_1_1.sizePolicy().hasHeightForWidth())
        self.basis_1_1.setSizePolicy(sizePolicy)
        self.basis_1_1.setMinimumSize(QtCore.QSize(39, 0))
        self.basis_1_1.setMaximumSize(QtCore.QSize(40, 25))
        self.basis_1_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.basis_1_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.basis_1_1.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.basis_1_1.setObjectName("basis_1_1")
        self.horizontalLayout_2.addWidget(self.basis_1_1)
        self.basis_1_2 = QtWidgets.QPlainTextEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basis_1_2.sizePolicy().hasHeightForWidth())
        self.basis_1_2.setSizePolicy(sizePolicy)
        self.basis_1_2.setMinimumSize(QtCore.QSize(0, 25))
        self.basis_1_2.setMaximumSize(QtCore.QSize(40, 25))
        self.basis_1_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.basis_1_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.basis_1_2.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.basis_1_2.setObjectName("basis_1_2")
        self.horizontalLayout_2.addWidget(self.basis_1_2)
        self.basis_1_3 = QtWidgets.QPlainTextEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basis_1_3.sizePolicy().hasHeightForWidth())
        self.basis_1_3.setSizePolicy(sizePolicy)
        self.basis_1_3.setMaximumSize(QtCore.QSize(40, 25))
        self.basis_1_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.basis_1_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.basis_1_3.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.basis_1_3.setObjectName("basis_1_3")
        self.horizontalLayout_2.addWidget(self.basis_1_3)
        self.formLayout_4.setLayout(9, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_16 = QtWidgets.QLabel(self.page_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lattice_const_1 = QtWidgets.QTextEdit(self.page_2)
        self.lattice_const_1.setMaximumSize(QtCore.QSize(133, 25))
        self.lattice_const_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lattice_const_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lattice_const_1.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.lattice_const_1.setObjectName("lattice_const_1")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lattice_const_1)
        self.label_17 = QtWidgets.QLabel(self.page_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.page_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.page_2)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(self.page_2)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.page_2)
        self.label_21.setObjectName("label_21")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(self.page_2)
        self.label_22.setObjectName("label_22")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.show_structure_spacegroup = QtWidgets.QPushButton(self.page_2)
        self.show_structure_spacegroup.setMinimumSize(QtCore.QSize(115, 0))
        self.show_structure_spacegroup.setObjectName("show_structure_spacegroup")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.show_structure_spacegroup)
        self.save_structure_spacegroup = QtWidgets.QPushButton(self.page_2)
        self.save_structure_spacegroup.setMaximumSize(QtCore.QSize(135, 16777215))
        self.save_structure_spacegroup.setObjectName("save_structure_spacegroup")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.save_structure_spacegroup)
        self.lattice_const_2 = QtWidgets.QPlainTextEdit(self.page_2)
        self.lattice_const_2.setMaximumSize(QtCore.QSize(133, 25))
        self.lattice_const_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lattice_const_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lattice_const_2.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.lattice_const_2.setObjectName("lattice_const_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lattice_const_2)
        self.lattice_const_3 = QtWidgets.QPlainTextEdit(self.page_2)
        self.lattice_const_3.setMaximumSize(QtCore.QSize(133, 25))
        self.lattice_const_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lattice_const_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lattice_const_3.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.lattice_const_3.setObjectName("lattice_const_3")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lattice_const_3)
        self.alpha = QtWidgets.QPlainTextEdit(self.page_2)
        self.alpha.setMaximumSize(QtCore.QSize(133, 25))
        self.alpha.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.alpha.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.alpha.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.alpha.setObjectName("alpha")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.alpha)
        self.beta = QtWidgets.QPlainTextEdit(self.page_2)
        self.beta.setMaximumSize(QtCore.QSize(133, 25))
        self.beta.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.beta.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.beta.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.beta.setObjectName("beta")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.beta)
        self.spacegroup = QtWidgets.QPlainTextEdit(self.page_2)
        self.spacegroup.setMinimumSize(QtCore.QSize(135, 25))
        self.spacegroup.setMaximumSize(QtCore.QSize(133, 16777215))
        self.spacegroup.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.spacegroup.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.spacegroup.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.spacegroup.setObjectName("spacegroup")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spacegroup)
        self.gamma = QtWidgets.QPlainTextEdit(self.page_2)
        self.gamma.setMaximumSize(QtCore.QSize(133, 25))
        self.gamma.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gamma.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gamma.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.gamma.setObjectName("gamma")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.gamma)
        self.add_element = QtWidgets.QPushButton(self.page_2)
        self.add_element.setMinimumSize(QtCore.QSize(115, 0))
        self.add_element.setAutoDefault(False)
        self.add_element.setDefault(False)
        self.add_element.setFlat(False)
        self.add_element.setObjectName("add_element")
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.add_element)
        self.verticalLayout.addLayout(self.formLayout_4)
        self.toolBox.addItem(self.page_2, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 472, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.toolBox.addItem(self.page_4, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lammps = QtWidgets.QRadioButton(self.page_3)
        self.lammps.setObjectName("lammps")
        self.verticalLayout_2.addWidget(self.lammps)
        self.vasp = QtWidgets.QRadioButton(self.page_3)
        self.vasp.setCheckable(True)
        self.vasp.setObjectName("vasp")
        self.verticalLayout_2.addWidget(self.vasp)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.toolBox.addItem(self.page_3, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.toolBox.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_23 = QtWidgets.QLabel(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_7.addWidget(self.label_23)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setContentsMargins(-1, -1, -1, 3)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_29 = QtWidgets.QLabel(self.page_6)
        self.label_29.setObjectName("label_29")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.temp_low = QtWidgets.QPlainTextEdit(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_low.sizePolicy().hasHeightForWidth())
        self.temp_low.setSizePolicy(sizePolicy)
        self.temp_low.setMinimumSize(QtCore.QSize(150, 25))
        self.temp_low.setMaximumSize(QtCore.QSize(203, 25))
        self.temp_low.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.temp_low.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.temp_low.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.temp_low.setObjectName("temp_low")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.temp_low)
        self.label_30 = QtWidgets.QLabel(self.page_6)
        self.label_30.setObjectName("label_30")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.temp_high = QtWidgets.QPlainTextEdit(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_high.sizePolicy().hasHeightForWidth())
        self.temp_high.setSizePolicy(sizePolicy)
        self.temp_high.setMinimumSize(QtCore.QSize(0, 25))
        self.temp_high.setMaximumSize(QtCore.QSize(203, 25))
        self.temp_high.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.temp_high.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.temp_high.setDocumentTitle("")
        self.temp_high.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.temp_high.setOverwriteMode(False)
        self.temp_high.setObjectName("temp_high")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.temp_high)
        self.label_31 = QtWidgets.QLabel(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(0, 25))
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_31.setObjectName("label_31")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.temp_step = QtWidgets.QPlainTextEdit(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_step.sizePolicy().hasHeightForWidth())
        self.temp_step.setSizePolicy(sizePolicy)
        self.temp_step.setMinimumSize(QtCore.QSize(0, 25))
        self.temp_step.setMaximumSize(QtCore.QSize(203, 25))
        self.temp_step.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.temp_step.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.temp_step.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.temp_step.setObjectName("temp_step")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.temp_step)
        self.verticalLayout_7.addLayout(self.formLayout_5)
        self.label_24 = QtWidgets.QLabel(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_7.addWidget(self.label_24)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_26 = QtWidgets.QLabel(self.page_6)
        self.label_26.setObjectName("label_26")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.press_low = QtWidgets.QPlainTextEdit(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_low.sizePolicy().hasHeightForWidth())
        self.press_low.setSizePolicy(sizePolicy)
        self.press_low.setMinimumSize(QtCore.QSize(0, 25))
        self.press_low.setMaximumSize(QtCore.QSize(203, 25))
        self.press_low.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.press_low.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.press_low.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.press_low.setObjectName("press_low")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.press_low)
        self.label_27 = QtWidgets.QLabel(self.page_6)
        self.label_27.setObjectName("label_27")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.press_high = QtWidgets.QPlainTextEdit(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_high.sizePolicy().hasHeightForWidth())
        self.press_high.setSizePolicy(sizePolicy)
        self.press_high.setMinimumSize(QtCore.QSize(0, 25))
        self.press_high.setMaximumSize(QtCore.QSize(203, 25))
        self.press_high.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.press_high.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.press_high.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.press_high.setObjectName("press_high")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.press_high)
        self.label_28 = QtWidgets.QLabel(self.page_6)
        self.label_28.setObjectName("label_28")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.press_step = QtWidgets.QPlainTextEdit(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_step.sizePolicy().hasHeightForWidth())
        self.press_step.setSizePolicy(sizePolicy)
        self.press_step.setMinimumSize(QtCore.QSize(0, 25))
        self.press_step.setMaximumSize(QtCore.QSize(203, 25))
        self.press_step.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.press_step.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.press_step.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.press_step.setOverwriteMode(False)
        self.press_step.setObjectName("press_step")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.press_step)
        self.verticalLayout_7.addLayout(self.formLayout_6)
        self.label_32 = QtWidgets.QLabel(self.page_6)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_7.addWidget(self.label_32)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_25 = QtWidgets.QLabel(self.page_6)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_3.addWidget(self.label_25)
        self.ionic_steps = QtWidgets.QPlainTextEdit(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ionic_steps.sizePolicy().hasHeightForWidth())
        self.ionic_steps.setSizePolicy(sizePolicy)
        self.ionic_steps.setMinimumSize(QtCore.QSize(0, 25))
        self.ionic_steps.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ionic_steps.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ionic_steps.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.ionic_steps.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.ionic_steps.setObjectName("ionic_steps")
        self.horizontalLayout_3.addWidget(self.ionic_steps)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 214, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.toolBox.addItem(self.page_6, "")
        self.simulation_setup.addWidget(self.toolBox)
        self.horizontalLayout.addLayout(self.simulation_setup)
        self.simulation_layout = QtWidgets.QVBoxLayout()
        self.simulation_layout.setObjectName("simulation_layout")
        self.run_simulation_layout = QtWidgets.QHBoxLayout()
        self.run_simulation_layout.setObjectName("run_simulation_layout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.run_simulation_layout.addItem(spacerItem4)
        self.run = QtWidgets.QPushButton(self.centralwidget)
        self.run.setObjectName("run")
        self.run_simulation_layout.addWidget(self.run)
        self.supercomp_run = QtWidgets.QPushButton(self.centralwidget)
        self.supercomp_run.setObjectName("supercomp_run")
        self.run_simulation_layout.addWidget(self.supercomp_run)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.run_simulation_layout.addItem(spacerItem5)
        self.simulation_layout.addLayout(self.run_simulation_layout)
        self.output = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output.sizePolicy().hasHeightForWidth())
        self.output.setSizePolicy(sizePolicy)
        self.output.setTabsClosable(True)
        self.output.setObjectName("output")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.tab)
        self.openGLWidget.setGeometry(QtCore.QRect(200, 130, 300, 200))
        self.openGLWidget.setObjectName("openGLWidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(190, 440, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.output.addTab(self.tab, "")
        self.simulation_layout.addWidget(self.output)
        self.horizontalLayout.addLayout(self.simulation_layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_Job = QtWidgets.QAction(MainWindow)
        self.actionSave_Job.setObjectName("actionSave_Job")
        self.menuFile.addAction(self.actionSave_Job)
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        self.output.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pyiron Simulation"))
        self.label.setText(_translate("MainWindow", "Path"))
        self.path.setText(_translate("MainWindow", "Select Path"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "File/Name"))
        self.label_3.setText(_translate("MainWindow", "Create Structure"))
        self.label_6.setText(_translate("MainWindow", "Name"))
        self.label_7.setText(_translate("MainWindow", "Bravais Lattice"))
        self.bravais_lattice.setItemText(1, _translate("MainWindow", "scc"))
        self.bravais_lattice.setItemText(2, _translate("MainWindow", "fcc"))
        self.bravais_lattice.setItemText(3, _translate("MainWindow", "bcc"))
        self.label_8.setText(_translate("MainWindow", "Lattice Constant"))
        self.show_structure_norm.setText(_translate("MainWindow", "Show Structure"))
        self.save_structure_norm.setText(_translate("MainWindow", "Save Structure"))
        self.label_4.setText(_translate("MainWindow", "Create ASE Bulk"))
        self.label_9.setText(_translate("MainWindow", "Name"))
        self.label_10.setText(_translate("MainWindow", "Crystal Structure"))
        self.label_11.setText(_translate("MainWindow", "Lattice Constant"))
        self.label_12.setText(_translate("MainWindow", "Crystal System"))
        self.show_structure_bulk.setText(_translate("MainWindow", "Show Structure"))
        self.save_structure_bulk.setText(_translate("MainWindow", "Save Structure"))
        self.crystal_structure.setItemText(1, _translate("MainWindow", "wurtzite"))
        self.crystal_system.setItemText(1, _translate("MainWindow", "Cubic"))
        self.crystal_system.setItemText(2, _translate("MainWindow", "Orthorhombic"))
        self.label_5.setText(_translate("MainWindow", "ASE Spacegroup"))
        self.label_13.setText(_translate("MainWindow", "Name"))
        self.label_14.setText(_translate("MainWindow", "Element 1"))
        self.label_15.setText(_translate("MainWindow", "Basis 1"))
        self.label_16.setText(_translate("MainWindow", "Lattice Const 1"))
        self.label_17.setText(_translate("MainWindow", "Lattice Const 2"))
        self.label_18.setText(_translate("MainWindow", "Lattice Const 3"))
        self.label_19.setText(_translate("MainWindow", "alpha"))
        self.label_20.setText(_translate("MainWindow", "beta"))
        self.label_21.setText(_translate("MainWindow", "gamma"))
        self.label_22.setText(_translate("MainWindow", "Spacegroup"))
        self.show_structure_spacegroup.setText(_translate("MainWindow", "Show Structure"))
        self.save_structure_spacegroup.setText(_translate("MainWindow", "Save Structure"))
        self.add_element.setText(_translate("MainWindow", "Add Element"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Create Structure"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Select Structure"))
        self.lammps.setText(_translate("MainWindow", "LAMMPS"))
        self.vasp.setText(_translate("MainWindow", "VASP"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Job Type"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "Potential Selection"))
        self.label_23.setText(_translate("MainWindow", "Temperature"))
        self.label_29.setText(_translate("MainWindow", "Low"))
        self.label_30.setText(_translate("MainWindow", "High"))
        self.temp_high.setPlaceholderText(_translate("MainWindow", "NA"))
        self.label_31.setText(_translate("MainWindow", "Step Size"))
        self.temp_step.setPlaceholderText(_translate("MainWindow", "NA"))
        self.label_24.setText(_translate("MainWindow", "Pressure"))
        self.label_26.setText(_translate("MainWindow", "Low"))
        self.label_27.setText(_translate("MainWindow", "High"))
        self.press_high.setPlaceholderText(_translate("MainWindow", "NA"))
        self.label_28.setText(_translate("MainWindow", "Step Size"))
        self.press_step.setPlaceholderText(_translate("MainWindow", "NA"))
        self.label_32.setText(_translate("MainWindow", "Ionic Steps"))
        self.label_25.setText(_translate("MainWindow", "Num Step"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("MainWindow", "Parameters"))
        self.run.setText(_translate("MainWindow", "Run Simulation"))
        self.supercomp_run.setText(_translate("MainWindow", "Send Job to Supercomputer"))
        self.output.setTabText(self.output.indexOf(self.tab), _translate("MainWindow", "Page"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open Job"))
        self.actionSave_Job.setText(_translate("MainWindow", "Save Job"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

